// This question's implementation is unfortunately fully unfinished, however all of our other programs showcase what were were going for regarding the design of syntax, that we will be showcasing in the qualitative 50% half of this coursework / the report.
