READ = “network.n4j”

MATCH = persons-r->friend | friend'-r'->employer
WHERE 
    =   persons.name      starts "A"
    OR  persons.name      starts "B"
    OR  persons.name      starts "C"
    AND persons:LABEL     ==     "Person"
    AND friend:LABEL      ==     "Person"
    AND persons:age       <      friend:age

    AND employer:LABEL    ==     "Employer"
    AND r:TYPE            ==     "isFriend"
    AND r':TYPE           ==     "WorksFor"

    AND friend:ID         ==     friend':ID

RETURN_NODE 
    = persons.
    | friend

RETURN_RELATION