READ = “loyalty.n4j”
MATCH = a-r->b
WHERE
    = r:TYPE == "Recommended
RETURN 


MATCH p-c->b | p'-r->q | q'-c'->b'

WHERE
    =   a:ID == a':ID
    AND q:ID == q':ID
    AND b:ID == b':ID

    AND c:TYPE == "CustomerOf"
    AND c':TYPE == "CustomerOf"
    AND r:TYPE == "Recommended"

fat pattern matching



Read = "loyalty.n4j"
MATCH =  match relationships 3 variables , but chained together 
Where = a.id, b.id blah blah, so the id's values of the relationships, equaating that to c, or d or smth 


UPDATE things, where he has pipes, so you can pip in ndoes, he access all the datatypes and values he needed with the name of the variable, match , 

 += operator that adds and equates two numbers, 

Delete at th end, that deletes 

DELETE Recommended, this can be chained, so you can multiple things, can has the ability to delete labels if needed 





READ "loyalty.n4j"
MATCH a--x--b, c --y--d
WHERE  a.id = c
UPDATE 
DELETE Recommended 











UPDATE 
    =   c:START_ID == p:ID , c.reward ++ b.bonus , c:END_ID, c:TYPE 
    |   c':START_ID == q':ID , c'.reward ++ b.bonus , c':END_ID, c':TYPE 
DELETE 
    = Recommended
