READ = "gems.n4j"

// MAX is an unimplemented feature 

MATCH = customer | gem
WHERE
    =   (customer.gem /= "" AND gem.name /= "") 
    AND (customer.wealth >= gem.value) 
    AND (customer:LABEL == gem:LABEL)
    AND (MAX gem.value)

RETURN = customer:ID--Purchases--gem:ID